namespace app
{
	//Internal requests start with the last value of ApiRequest enum.
	BEGIN_ENUM(ApiInternalRequest)
		ENUM_WITH_VALUE(ApiInternalRequest, ApiInternalRequest_Cancel, ApiRequest_UNKNOWN)
	END_ENUM(ApiInternalRequest)
		
	BEGIN_ENUM(ApiError)
		ENUM(ApiError, ApiSuccess)
		ENUM(ApiError, ApiErrorLibSetup)
		ENUM(ApiError, ApiErrorAlreadyInitialized)
		ENUM(ApiError, ApiErrorLibTeardown)
		ENUM(ApiError, ApiErrorNullArgument)
		ENUM(ApiError, ApiErrorNullContent)
		ENUM(ApiError, ApiErrorInvalidHandle)
		ENUM(ApiError, ApiErrorWrongHandleType)
		ENUM(ApiError, ApiErrorHandleNotFound)
		ENUM(ApiError, ApiErrorInvalidDate)
		ENUM(ApiError, ApiErrorInvalidFactors)
		ENUM(ApiError, ApiErrorMismatchedDateSpec)
		ENUM(ApiError, ApiErrorInvalidCurveInput)
		ENUM(ApiError, ApiErrorInvalidFormat)
		ENUM(ApiError, ApiErrorInvalidLength)
		ENUM(ApiError, ApiErrorMissingHpiData)
		ENUM(ApiError, ApiErrorMissingUnemploymentData)
		ENUM(ApiError, ApiErrorMissingPrimaryRates)
		ENUM(ApiError, ApiErrorMissingSecondaryRates)
		ENUM(ApiError, ApiErrorMissingRawCurveInput)
		ENUM(ApiError, ApiErrorMissingInstrumentPortfolio)
		ENUM(ApiError, ApiErrorMissingVolatilityStructureInput)
		ENUM(ApiError, ApiErrorMissingModelOptions)
		ENUM(ApiError, ApiErrorEmptyTenors)
		ENUM(ApiError, ApiErrorEmptyExpiries)
		ENUM(ApiError, ApiErrorInvalidModelParameter)
		ENUM(ApiError, ApiErrorInvalidSessionParameter)
		ENUM(ApiError, ApiErrorMismatchedModelType)
		ENUM(ApiError, ApiErrorInvalidModelType)
		ENUM(ApiError, ApiErrorInvalidRequestType)
		ENUM(ApiError, ApiErrorInvalidHistoricalData)
		ENUM(ApiError, ApiErrorOutOfRange)
		ENUM(ApiError, ApiErrorNumPathsOutOfRange)
		ENUM(ApiError, ApiErrorPathLengthMismatch)
		ENUM(ApiError, ApiErrorEmptyOutput)
		ENUM(ApiError, ApiErrorEmptyRates)
		ENUM(ApiError, ApiErrorSend)
		ENUM(ApiError, ApiErrorReceive)
		ENUM(ApiError, ApiErrorException)
		ENUM(ApiError, ApiErrorMismatchedGenMethod)
		ENUM(ApiError, ApiErrorTimeout)
		ENUM(ApiError, ApiErrorInvalidTimeout)
		ENUM(ApiError, ApiErrorOperationCancelled)
		ENUM(ApiError, ApiErrorOperationNotSupported)
		ENUM(ApiError, ApiErrorNotCancellable)
		ENUM(ApiError, ApiErrorRequestNotFound)
		ENUM(ApiError, ApiErrorNoMoreData)
		ENUM(ApiError, ApiErrorNoRatesFiles)
		ENUM(ApiError, ApiErrorInvalidRatesFiles)
	END_ENUM(ApiError)

	//DO NOT REORDER!! 
	//Updates to this enum must be reflected in HandleTypeSelection type.
	BEGIN_ENUM_CLASS(HandleType)
		ENUM_WITH_VALUE(HandleType, Any, 0)
		//Requests
		ENUM_WITH_VALUE(HandleType, GenRatePathsForMortgageValuationRequest, ApiRequest_GenRatePathsForMortgageValuation)
		ENUM_WITH_VALUE(HandleType, CalcValueForMortgageRequest, ApiRequest_CalcValueForMortgage)
		ENUM_WITH_VALUE(HandleType, CalcValueForMortgageWithSofrRatesRequest, ApiRequest_CalcValueForMortgageWithSofrRates)
		ENUM_WITH_VALUE(HandleType, CalcGreeksFromPricesRequest, ApiRequest_CalcGreeksFromPrices)
		ENUM_WITH_VALUE(HandleType, AttribValueChangeByWaterfallRequest, ApiRequest_AttribValueChangeByWaterfall)
		ENUM_WITH_VALUE(HandleType, GenPrimaryMortgageRatePathsRequest, ApiRequest_GenPrimaryMortgageRatePaths)
		ENUM_WITH_VALUE(HandleType, GenSecondaryMortgageRatePathsRequest, ApiRequest_GenSecondaryMortgageRatePaths)
		ENUM_WITH_VALUE(HandleType, CalcValueForMonthEndRollRequest, ApiRequest_CalcValueForMonthEndRoll)
		ENUM_WITH_VALUE(HandleType, GeneratePathForWaterfallAttributionRequest, ApiRequest_GenRatePathsForWaterfallAttribution)
		ENUM_WITH_VALUE(HandleType, CalcBehavioralSpeedFromPrimaryRateRequest, ApiRequest_CalcBehavioralSpeedFromPrimaryRate)
		ENUM_WITH_VALUE(HandleType, CalcValueForMortgageFromRatesRequest, ApiRequest_CalcValueForMortgageFromRates)
		ENUM_WITH_VALUE(HandleType, CalcProfitabilityFromBehavioralSpeedsRequest, ApiRequest_CalcProfitabilityFromBehavioralSpeeds)
		ENUM_WITH_VALUE(HandleType, CancelRequest, ApiInternalRequest_Cancel)
		//Other
		ENUM(HandleType, HandleArray)
		ENUM(HandleType, DateSpec)
		ENUM(HandleType, MarketData)
		ENUM(HandleType, HistoricalData)
		ENUM(HandleType, FloatingPointMatrix)
		ENUM(HandleType, RatePathCollection)
		ENUM(HandleType, GreekSpec)
		ENUM(HandleType, Portfolio)
		ENUM(HandleType, ModelSpec)
		ENUM(HandleType, SessionSpec)
		ENUM(HandleType, ModelOptions)
		ENUM(HandleType, TenorRatePathsMap)
		ENUM(HandleType, SofrRatePaths)
		ENUM(HandleType, UserScenarios)
		ENUM(HandleType, VolatilityBasket)
		ENUM(HandleType, CurveModificationSpec)
		ENUM(HandleType, CurveInterpolationSpec)
		ENUM(HandleType, ExecOptions)
		ENUM(HandleType, PricingSpec)
		ENUM(HandleType, PrimaryRateOverride)
		ENUM(HandleType, ParamFileVersionResolver)
		ENUM(HandleType, ModelConfigData)
		ENUM(HandleType, RequestContextData)
		ENUM(HandleType, ResultData)
		ENUM(HandleType, CalcRatePaths)
	END_ENUM_CLASS(HandleType)

	/*
		HandleBinding enum represents setter functions which are created when any API call
		establishes a relationship (binding) between two handles e.g. bindModelSession().
		These setter functions will be called before the request is executed
		to update the entire object from its bindings.
	*/
	BEGIN_ENUM_CLASS(HandleBinding)
		ENUM(HandleBinding, CancelRequest)
		ENUM(HandleBinding, DateSpec)
		ENUM(HandleBinding, MarketData)
		ENUM(HandleBinding, EndMarketData)
		ENUM(HandleBinding, HistoricalData)
		ENUM(HandleBinding, ModelSession)
		ENUM(HandleBinding, Portfolio)
		ENUM(HandleBinding, ModelOptions)
		ENUM(HandleBinding, SofrRatePathsOrGenSpec)
		ENUM(HandleBinding, Scenarios)
		ENUM(HandleBinding, GreekSpec)
		ENUM(HandleBinding, ModelSpec)
		ENUM(HandleBinding, PrimaryRateModel)
		ENUM(HandleBinding, SecondaryRateModel)
		ENUM(HandleBinding, PrepayModel)
		ENUM(HandleBinding, LossModel)
		ENUM(HandleBinding, InterestRateModel)
		ENUM(HandleBinding, CashflowModel)
		ENUM(HandleBinding, DiscountingModel)
		ENUM(HandleBinding, CalibrationBasket)
		ENUM(HandleBinding, CashRates)
		ENUM(HandleBinding, SwapRates)
		ENUM(HandleBinding, CurveModificationSpec)
		ENUM(HandleBinding, CurveInterpolationSpec)
	    ENUM(HandleBinding, ExecOptions)
		ENUM(HandleBinding, PricingSpec)
	    ENUM(HandleBinding, PrimaryRateInputs)
		ENUM(HandleBinding, ParamFileVersionResolver)
		ENUM(HandleBinding, OverrideRatePaths)
	END_ENUM_CLASS(HandleBinding)

}
